/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type DepartmentFacts = {
  _id: string;
  _type: 'departmentFacts';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  missionStatement?: string;
  foundedYear?: number;
  volunteerCount?: number;
  squareMiles?: number;
};

export type DistrictFacts = {
  _id: string;
  _type: 'districtFacts';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  millRate?: number;
  districtMailing?: string;
  fundingNoteTitle?: string;
  fundingNote?: string;
};

export type MeetingSchedule = {
  _id: string;
  _type: 'meetingSchedule';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  meetingWeekOfMonth?: 1 | 2 | 3 | 4 | -1;
  meetingWeekday?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  meetingTime?: string;
  meetingLocation?: string;
};

export type AlertBanner = {
  _id: string;
  _type: 'alertBanner';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  alertEnabled?: boolean;
  alertLevel?: 'redflag' | 'burnban';
  alertTag?: string;
  alertMessage?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  phoneNonEmergency?: string;
  phoneStateRadio?: string;
  email?: string;
  boardEmail?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SeasonalTip = {
  _id: string;
  _type: 'seasonalTip';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  season: 'Spring' | 'Summer' | 'Fall' | 'Winter';
  tip: string;
  order?: number;
};

export type Happening = {
  _id: string;
  _type: 'happening';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  caption?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type PreventionTopic = {
  _id: string;
  _type: 'preventionTopic';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  kicker?: string;
  summary?: string;
  cards?: Array<{
    heading: string;
    points?: Array<string>;
    _type: 'tipCard';
    _key: string;
  }>;
  order?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type StationReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'station';
};

export type Apparatus = {
  _id: string;
  _type: 'apparatus';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  unitType?: 'Engine' | 'Tender' | 'Brush / Grass' | 'Rescue' | 'Command' | 'Support' | 'Other';
  year?: number;
  chassis?: string;
  tankCapacity?: number;
  pumpCapacity?: number;
  station?: StationReference;
  notes?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  order?: number;
};

export type Officer = {
  _id: string;
  _type: 'officer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  rank: string;
  yearsOfService?: number;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  order?: number;
};

export type Vote = {
  _id: string;
  _type: 'vote';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  summary: string;
  votingInfo?: string;
  link?: string;
  outcome?: 'passed' | 'failed';
  resultSummary?: string;
};

export type TownshipReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'township';
};

export type BoardMember = {
  _id: string;
  _type: 'boardMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: 'President' | 'Vice President' | 'Treasurer' | 'Director';
  township?: TownshipReference;
  email?: string;
  phone?: string;
  preferredContact?: 'email' | 'phone';
  lastElected?: number;
  order?: number;
};

export type Township = {
  _id: string;
  _type: 'township';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type Meeting = {
  _id: string;
  _type: 'meeting';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  date: string;
  title: string;
  slug: Slug;
  time?: string;
  locationType?: 'station' | 'other';
  station?: StationReference;
  otherLocation?: string;
  agendaBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  agendaPdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  minutesBody?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  minutesPdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  minutesStatus?: string;
};

export type Station = {
  _id: string;
  _type: 'station';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  address?: string;
  mailingAddress?: string;
  isHeadquarters?: boolean;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  notes?: string;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | DepartmentFacts
  | DistrictFacts
  | MeetingSchedule
  | AlertBanner
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SeasonalTip
  | Happening
  | PreventionTopic
  | Slug
  | StationReference
  | Apparatus
  | Officer
  | Vote
  | TownshipReference
  | BoardMember
  | Township
  | SanityFileAssetReference
  | Meeting
  | Station
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: MEETINGS_QUERY
// Query: *[_type == "meeting"] | order(date desc){  "slug": slug.current,  date, title, time, locationType, otherLocation,  "stationName": station->name,  "stationAddress": station->address,  agendaBody, minutesBody, minutesStatus,  "agendaPdfUrl": agendaPdf.asset->url,  "minutesPdfUrl": minutesPdf.asset->url}
export type MEETINGS_QUERY_RESULT = Array<{
  slug: string;
  date: string;
  title: string;
  time: string | null;
  locationType: 'other' | 'station' | null;
  otherLocation: string | null;
  stationName: string | null;
  stationAddress: string | null;
  agendaBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  minutesBody: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  minutesStatus: string | null;
  agendaPdfUrl: string | null;
  minutesPdfUrl: string | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: BOARD_QUERY
// Query: *[_type == "boardMember"] | order(order asc){  name, role, email, phone, preferredContact, lastElected,  "township": township->name}
export type BOARD_QUERY_RESULT = Array<{
  name: string;
  role: 'Director' | 'President' | 'Treasurer' | 'Vice President';
  email: string | null;
  phone: string | null;
  preferredContact: 'email' | 'phone' | null;
  lastElected: number | null;
  township: string | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: TOWNSHIPS_QUERY
// Query: *[_type == "township"] | order(name asc){  name}
export type TOWNSHIPS_QUERY_RESULT = Array<{
  name: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: UPCOMING_VOTES_QUERY
// Query: *[_type == "vote" && date >= $today] | order(date asc){  title, date, summary, votingInfo, link}
export type UPCOMING_VOTES_QUERY_RESULT = Array<{
  title: string;
  date: string;
  summary: string;
  votingInfo: string | null;
  link: string | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: PAST_VOTES_QUERY
// Query: *[_type == "vote" && date < $today] | order(date desc){  title, date, summary, outcome, resultSummary}
export type PAST_VOTES_QUERY_RESULT = Array<{
  title: string;
  date: string;
  summary: string;
  outcome: 'failed' | 'passed' | null;
  resultSummary: string | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: OFFICERS_QUERY
// Query: *[_type == "officer"] | order(order asc){  name, rank, yearsOfService, photo}
export type OFFICERS_QUERY_RESULT = Array<{
  name: string;
  rank: string;
  yearsOfService: number | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: STATIONS_QUERY
// Query: *[_type == "station"] | order(order asc){  _id, name, address, mailingAddress, isHeadquarters, photo, notes,  "apparatus": *[_type == "apparatus" && station._ref == ^._id] | order(order asc){    _id, name, unitType, year, chassis, tankCapacity, pumpCapacity, notes, photo  }}
export type STATIONS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  address: string | null;
  mailingAddress: string | null;
  isHeadquarters: boolean | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  notes: string | null;
  apparatus: Array<{
    _id: string;
    name: string;
    unitType:
      'Brush / Grass' | 'Command' | 'Engine' | 'Other' | 'Rescue' | 'Support' | 'Tender' | null;
    year: number | null;
    chassis: string | null;
    tankCapacity: number | null;
    pumpCapacity: number | null;
    notes: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    } | null;
  }>;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: PREVENTION_QUERY
// Query: *[_type == "preventionTopic"] | order(order asc){  _id, title, "slug": slug.current, kicker, summary,  cards[]{ heading, points }}
export type PREVENTION_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  kicker: string | null;
  summary: string | null;
  cards: Array<{
    heading: string;
    points: Array<string> | null;
  }> | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: HAPPENINGS_QUERY
// Query: *[_type == "happening"] | order(date desc)[0...$limit]{  title, caption, photo}
export type HAPPENINGS_QUERY_RESULT = Array<{
  title: string;
  caption: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: SEASONAL_TIPS_QUERY
// Query: *[_type == "seasonalTip" && season == $season] | order(order asc){  tip}
export type SEASONAL_TIPS_QUERY_RESULT = Array<{
  tip: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  phoneNonEmergency, phoneStateRadio, email, boardEmail,  heroImage}
export type SETTINGS_QUERY_RESULT = {
  phoneNonEmergency: string | null;
  phoneStateRadio: string | null;
  email: string | null;
  boardEmail: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: ALERT_QUERY
// Query: *[_type == "alertBanner"][0]{  alertEnabled, alertLevel, alertTag, alertMessage}
export type ALERT_QUERY_RESULT = {
  alertEnabled: boolean | null;
  alertLevel: 'burnban' | 'redflag' | null;
  alertTag: string | null;
  alertMessage: string | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: SCHEDULE_QUERY
// Query: *[_type == "meetingSchedule"][0]{  meetingWeekOfMonth, meetingWeekday, meetingTime, meetingLocation}
export type SCHEDULE_QUERY_RESULT = {
  meetingWeekOfMonth: -1 | 1 | 2 | 3 | 4 | null;
  meetingWeekday: 0 | 1 | 2 | 3 | 4 | 5 | 6 | null;
  meetingTime: string | null;
  meetingLocation: string | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: DEPARTMENT_FACTS_QUERY
// Query: *[_type == "departmentFacts"][0]{  missionStatement, foundedYear, volunteerCount, squareMiles}
export type DEPARTMENT_FACTS_QUERY_RESULT = {
  missionStatement: string | null;
  foundedYear: number | null;
  volunteerCount: number | null;
  squareMiles: number | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: DISTRICT_FACTS_QUERY
// Query: *[_type == "districtFacts"][0]{  millRate, districtMailing, fundingNoteTitle, fundingNote}
export type DISTRICT_FACTS_QUERY_RESULT = {
  millRate: number | null;
  districtMailing: string | null;
  fundingNoteTitle: string | null;
  fundingNote: string | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "meeting"] | order(date desc){\n  "slug": slug.current,\n  date, title, time, locationType, otherLocation,\n  "stationName": station->name,\n  "stationAddress": station->address,\n  agendaBody, minutesBody, minutesStatus,\n  "agendaPdfUrl": agendaPdf.asset->url,\n  "minutesPdfUrl": minutesPdf.asset->url\n}': MEETINGS_QUERY_RESULT;
    '*[_type == "boardMember"] | order(order asc){\n  name, role, email, phone, preferredContact, lastElected,\n  "township": township->name\n}': BOARD_QUERY_RESULT;
    '*[_type == "township"] | order(name asc){\n  name\n}': TOWNSHIPS_QUERY_RESULT;
    '*[_type == "vote" && date >= $today] | order(date asc){\n  title, date, summary, votingInfo, link\n}': UPCOMING_VOTES_QUERY_RESULT;
    '*[_type == "vote" && date < $today] | order(date desc){\n  title, date, summary, outcome, resultSummary\n}': PAST_VOTES_QUERY_RESULT;
    '*[_type == "officer"] | order(order asc){\n  name, rank, yearsOfService, photo\n}': OFFICERS_QUERY_RESULT;
    '*[_type == "station"] | order(order asc){\n  _id, name, address, mailingAddress, isHeadquarters, photo, notes,\n  "apparatus": *[_type == "apparatus" && station._ref == ^._id] | order(order asc){\n    _id, name, unitType, year, chassis, tankCapacity, pumpCapacity, notes, photo\n  }\n}': STATIONS_QUERY_RESULT;
    '*[_type == "preventionTopic"] | order(order asc){\n  _id, title, "slug": slug.current, kicker, summary,\n  cards[]{ heading, points }\n}': PREVENTION_QUERY_RESULT;
    '*[_type == "happening"] | order(date desc)[0...$limit]{\n  title, caption, photo\n}': HAPPENINGS_QUERY_RESULT;
    '*[_type == "seasonalTip" && season == $season] | order(order asc){\n  tip\n}': SEASONAL_TIPS_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  phoneNonEmergency, phoneStateRadio, email, boardEmail,\n  heroImage\n}': SETTINGS_QUERY_RESULT;
    '*[_type == "alertBanner"][0]{\n  alertEnabled, alertLevel, alertTag, alertMessage\n}': ALERT_QUERY_RESULT;
    '*[_type == "meetingSchedule"][0]{\n  meetingWeekOfMonth, meetingWeekday, meetingTime, meetingLocation\n}': SCHEDULE_QUERY_RESULT;
    '*[_type == "departmentFacts"][0]{\n  missionStatement, foundedYear, volunteerCount, squareMiles\n}': DEPARTMENT_FACTS_QUERY_RESULT;
    '*[_type == "districtFacts"][0]{\n  millRate, districtMailing, fundingNoteTitle, fundingNote\n}': DISTRICT_FACTS_QUERY_RESULT;
  }
}
